export const TOGGLE_IS_LOADER = 'TOGGLE_IS_LOADER';
export const SET_RICK_AND_MORTY_LOCATION ='SET_RICK_AND_MORTY_LOCATION'
export const SET_RICK_AND_MORTY_CHARACTER='SET_RICK_AND_MORTY_CHARACTER'
export const SET_RICK_AND_MORTY_EPISODE='SET_RICK_AND_MORTY_EPISODE'
